### ISSUE TITLE
Architecture and Design

### ISSUE THREAD

**Issue by bnonni** [bnonni/drpm.tools#2]
### Goals

Meet users where they are. Make it simple. Make dev experience as smooth and seamless as possible. Make dpm as invisible as possible by default, so devs can just install dpm into their global env or local project and use npm like normal to interact with normal npm project related things but also toggle to work with dpm things. To do this, we can either have npm use dpm or vice versa. The former is ideal since devs already know that interface and don't need to learn anything new. The latter is more achievable and the interface can be designed to be identical to npm, so transitioning is easy. 

### Terminology

* P1 = Problem 1
* S1 = Solution to Problem 1
* X1 = Explanation of Solution 1
* DPM = Decentralized Package Manager
* DMI = Decentralized Module Import
* DPK = Decentralized Package
* DWN = Decentralized Web Node 

### Problems

* P1. How to structure dwn protocol and record schema
* P2. How to build custom dpm hooks to resolve and download DPKs
* P3. How to make npm use custom dpm hooks file to allow devs to use npm and interact with dpm
* P4. How to use dpm to interact with npm; inverse of P3
* P5. How to make node use custom dpm hooks file to allow devs to leverage dpm for `run` scripts

### Solutions

* [x] S1. See [protocol.ts](https://github.com/bnonni/dpm/blob/main/src/dwn/protocol.ts) and [package.ts](https://github.com/bnonni/dpm/blob/main/src/dwn/schema/package.ts)
* [x] S2.  See [dpm.ts](https://github.com/bnonni/dpm/blob/main/src/dpm.ts) and [register.ts](https://github.com/bnonni/dpm/blob/main/src/register.ts)
* [x] S3. Not possible. See X1. below.
* [x] S4. Build dpm cli to mimic and interact with npm (see X4. below) - #9
* [x] S5. Can update the `NODE_OPTIONS` env var (see X3. below).

### Explanations

* [x] ~X1. use npm to interact with dpm~
  * ~Example: `dpm install --foo --bar` executes `npm install --foo --bar --import ./register-hooks.js` under the hood~
  *  ~Doesn't appear that `npm install` has an import flag~
  * ~unfortunately, this isnt possible afaict~
  * ~`npm` does not provide any interface to pass custom files for doing various tasks like `run` or `install`~
* [x] ~X2. `dpm` imports `npm` via programmatic interface~
  * ~`preinstall=./path/to/your/register-hooks.js`~
  * ~by default, have `node` and `dpm` use this hook~
  * ~unfortunately, this isnt possible afaict~
  * ~programmatic api was disabled since node v8; cannot npm i npm and import commands to modules~
* [x] X3. dpm updates local `NODE_OPTIONS` env var using postinstall script
  * dpm executes child processes for npm commands
  * install.sh and postinstall script points local env to the register.ts file using the [--require flag](https://nodejs.org/api/module.html#customization-hooks) for custom hooks
  * if dpm installed globally with `npm i -g`  or individual project with `npm i`, postinstall script runs to set this up
  * if dpm installed via shell script, install.sh sets this up
  * if `NODE_OPTIONS` is set, update it to include register.js path; if `NODE_OPTIONS` is unset, set it to register.js path
  * `NODE_OPTIONS='--require /path/to/dpm/register.js'`
* [x] X4. use `child_process` to execute `npm` commands within the dpm module
  * all npm commands include `access, adduser, audit, bugs, cache, ci, completion, config, dedupe, deprecate, diff, dist-tag, docs, doctor, edit, exec, explain, explore, find-dupes, fund, get, help, help-search, hook, init, install, install-ci-test, install-test, link, ll, login, logout, ls, org, outdated, owner, pack, ping, pkg, prefix, profile, prune, publish, query, rebuild, repo, restart, root, run-script, sbom, search, set, shrinkwrap, star, stars, start, stop, team, test, token, uninstall, unpublish, unstar, update, version, view, whoami`
  * Do not need to augment all npm commands
  * Can simply proxy commands to a general dpm/npm function that calls `exec(npm ${command} ${...args}`
  * Need to proxy and add code for certain npm commands that are important for interacting with dPacks
    * `install/uninstall` - handles install/uninstall of nPacks and dPacks
    * `pack` - handles the packing of a dpm for publishing
    * `publish` - publishes a dPack to a DWN

### Architecture

* CLI
  * simple way to interact with DPM to install dWeb packages and run scripts with DMIs
  * npm -g
    * `npm i -g dpm`
    * installs dpm on local env making the cli globally accessible
  * curl install-dpm.sh
    * Users install DPM via `<curl -sSL | wget -qO- > https://dmp.software/install.sh | sh`
    * installs dpm on local env making the cli globally accessible
* MODULE
  * code published to npmjs.com that can be installed into local project
  * can use dpm in specific project without need to install cli into local env for global shell access/use
  * can augment project to interact with dPacks adhoc

**Comment by bnonni** [comment]
> ### Goals
> Meet users where they are. Make it simple. Make dev experience as smooth and seamless as possible. Make dpm as invisible as possible by default, so devs can just install dpm into their global env or local project and use npm like normal to interact with normal npm project related things but also toggle to work with dpm things. To do this, we can either have npm use dpm or vice versa. The former is ideal since devs already know that interface and don't need to learn anything new. The latter is more achievable and the interface can be designed to be identical to npm, so transitioning is easy.
> 
> ### Terminology
> * P1 = Problem 1
> * S1 = Solution to Problem 1
> * X1 = Explanation of Solution 1
> * DPM = Decentralized Package Manager
> * DMI = Decentralized Module Import
> * DPK = Decentralized Package
> * DWN = Decentralized Web Node
> 
> ### Problems
> * P1. How to structure dwn protocol and record schema
> * P2. How to build custom dpm hooks to resolve and download DPKs
> * P3. How to make npm use custom dpm hooks file to allow devs to use npm and interact with dpm
> * P4. How to use dpm to interact with npm; inverse of P3
> * P5. How to make node use custom dpm hooks file to allow devs to leverage dpm for `run` scripts
> 
> ### Solutions
> * [x]  S1. See [protocol.ts](https://github.com/bnonni/dpm/blob/main/src/dwn/protocol.ts) and [package.ts](https://github.com/bnonni/dpm/blob/main/src/dwn/schema/package.ts)
> * [x]  S2.  See [dpm.ts](https://github.com/bnonni/dpm/blob/main/src/dpm.ts) and [register.ts](https://github.com/bnonni/dpm/blob/main/src/register.ts)
> * [x]  S3. Not possible. See X1. below.
> * [ ]  S4. Build dpm cli to mimic and interact with npm (see X4. below) - [DPM CLI #9](https://github.com/bnonni/dpm.software/issues/9)
> * [ ]  S5. Can update the `NODE_OPTIONS` env var (see X3. below).
> 
> ### Explanations
> * [x]  ~X1. use npm to interact with dpm~
>   
>   * ~Example: `dpm install --foo --bar` executes `npm install --foo --bar --import ./register-hooks.js` under the hood~
>   * ~Doesn't appear that `npm install` has an import flag~
>   * ~unfortunately, this isnt possible afaict~
>   * ~`npm` does not provide any interface to pass custom files for doing various tasks like `run` or `install`~
> * [x]  ~X2. `dpm` imports `npm` via programmatic interface~
>   
>   * ~`preinstall=./path/to/your/register-hooks.js`~
>   * ~by default, have `node` and `dpm` use this hook~
>   * ~unfortunately, this isnt possible afaict~
>   * ~programmatic api was disabled since node v8; cannot npm i npm and import commands to modules~
> * [x]  X3. dpm updates local `NODE_OPTIONS` env var using postinstall script
>   
>   * dpm executes child processes for npm commands
>   * install.sh and postinstall script points local env to the register.ts file using the [--require flag](https://nodejs.org/api/module.html#customization-hooks) for custom hooks
>   * if dpm installed globally with `npm i -g`  or individual project with `npm i`, postinstall script runs to set this up
>   * if dpm installed via shell script, install.sh sets this up
>   * if `NODE_OPTIONS` is set, update it to include register.js path; if `NODE_OPTIONS` is unset, set it to register.js path
>   * `NODE_OPTIONS='--require /path/to/dpm/register.js'`
> * [x]  X4. use `child_process` to execute `npm` commands within the dpm module
>   
>   * all npm commands include `access, adduser, audit, bugs, cache, ci, completion, config, dedupe, deprecate, diff, dist-tag, docs, doctor, edit, exec, explain, explore, find-dupes, fund, get, help, help-search, hook, init, install, install-ci-test, install-test, link, ll, login, logout, ls, org, outdated, owner, pack, ping, pkg, prefix, profile, prune, publish, query, rebuild, repo, restart, root, run-script, sbom, search, set, shrinkwrap, star, stars, start, stop, team, test, token, uninstall, unpublish, unstar, update, version, view, whoami`
>   * Do not need to augment all npm commands
>   * Can simply proxy commands to a general dpm/npm function that calls `exec(npm ${command} ${...args}`
>   * Need to proxy and add code for certain npm commands that are important for interacting with dPacks
>     
>     * `install/uninstall` - handles install/uninstall of nPacks and dPacks
>     * `pack` - handles the packing of a dpm for publishing
>     * `publish` - publishes a dPack to a DWN
> 
> ### Architecture
> * CLI
>   
>   * simple way to interact with DPM to install dWeb packages and run scripts with DMIs
>   * npm -g
>     
>     * `npm i -g dpm`
>     * installs dpm on local env making the cli globally accessible
>   * curl install-dpm.sh
>     
>     * Users install DPM via `<curl -sSL | wget -qO- > https://dmp.software/install.sh | sh`
>     * installs dpm on local env making the cli globally accessible
> * MODULE
>   
>   * code published to npmjs.com that can be installed into local project
>   * can use dpm in specific project without need to install cli into local env for global shell access/use
>   * can augment project to interact with dPacks adhoc

The revised design and implementation is to reuse npm via `.npmrc` hooks prefixing all dpks with `@drpm`
This results in the CLI being much less necessary and focusing on building a local registry service to handle the GET calls.

Closing since a design/arch has been defined and is being implemented.

**Comment by zkochan** [comment]
I was also thinking about supporting a decentralized registry in pnpm: https://github.com/orgs/pnpm/discussions/3165. Unfortunately, I don't have enough knowledge at the moment to design such registry on my own but it is on my radar for sure.

I see that you mentioned how npm CLI doesn't allow to hook into it. Unlike npm, pnpm CLI does provide the possibility to hook into it by providing custom fetchers and soon [resolvers too](https://github.com/pnpm/pnpm/pull/9447). So I would recommend you to try hooking into pnpm instead of writing a new package manager from scratch.

I read the docs briefly, and I think I have a general understanding of the project. One thing that caught my eye is the ugly package names. I am not sure why the DID should be included in the package name. Probably it is to maintain maximum compatibility with npm CLI. I'd suggest using a new custom protocol instead or at least using aliases (this are supported by npm CLI too):

```json
"@drpm/tool5": "npm:@drpm/tool5~8w7ckznnw671az7nmkrd19ddctpj4spgt8sjqxkmnamdartxh1bo@^6.1.0",
```
